* Encoding: UTF-8.

DATASET ACTIVATE DataSet1.
GLM Intact Rearranged New BY Age
  /WSFACTOR=Association 3 Polynomial 
  /METHOD=SSTYPE(3)
  /EMMEANS=TABLES(Age) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(Association) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(Age*Association) COMPARE(Age) ADJ(BONFERRONI)
   /EMMEANS=TABLES(Age*Association) COMPARE(Association) ADJ(BONFERRONI)
  /PRINT=DESCRIPTIVE ETASQ HOMOGENEITY 
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=Association 
  /DESIGN=Age.
