* Encoding: UTF-8.

DATASET ACTIVATE DataSet1.
CORRELATIONS
  /VARIABLES=FaceRecognitionScore AssociationRecognitionScore
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

GLM FaceRecognitionScore AssociationRecognitionScore BY Age
  /METHOD=SSTYPE(3)
  /INTERCEPT=INCLUDE
  /EMMEANS=TABLES(Age) COMPARE ADJ(BONFERRONI)
  /PRINT=DESCRIPTIVE ETASQ HOMOGENEITY
  /CRITERIA=ALPHA(.05)
  /DESIGN= Age.
